### ISSUE TITLE
support for Mikrotik vendor via napalm-ros

### ISSUE THREAD

**Issue by fernandolcx** [tbotnz/netpalm#115]
I'm a beginner to network automation and I tried to use `napalm-ros` driver with a RouterBoard without success, nothing happens.

Is this something that need to be added in netpalm source code?

**Comment by tbotnz** [comment]
Hi @fernandolcx this should be easy to add by installing the driver and updating the driver, i don't see it as something we'd want in the netpalm-project itself but if you reach out to me on slack i can help you implement this
