### ISSUE TITLE
Auto reload of template directory

### ISSUE THREAD

**Issue by abrown-bw** [tbotnz/netpalm#130]
Templates are currently loaded on container creation and containers have to be re-built if the templates are edited. It would be ideal if the template directory was reloaded automatically after a certain time period or when a template has been changed.

**Comment by tbotnz** [comment]
Hey @abrown-bw, anything in **extensibles** can be added or deleted via the controllers REST endpoints, If its not clear from the swagger how this is done try the [postman collection](https://documenter.getpostman.com/view/2391814/T1DqgwcU?version=latest). These changes are then synchronized to all containers ( controllers are multi mastered ). If you then chose to scale out any of the contrainers the new extensibles will be added on the container turn up

**Comment by tbotnz** [comment]
also feel free to ask these questions on the #netpalm channel on networktocode slack

**Comment by tbotnz** [comment]
also forgot to mention theres another project #netpalm-admin which provides real time editing of templates in a webui on the running instance @abrown-bw @rhwendt

**Comment by rhwendt** [comment]
@tbotnz Cool thanks. Didnt realize you updated the postman collection :)
