### ISSUE TITLE
adding kafka support

### ISSUE THREAD

**Issue by wmclendon** [tbotnz/netpalm#132]
hello,

i mentioned in slack today but perhaps it is worth opening an issue here for discussion and posterity.

I think netpalm having native ability to publish the task result data to kafka topics would be very handy for various use cases for downstream consumption - especially when combined with the scheduled tasks - and at least functionally, i've been able to add it fairly easily by adding the library `kafka-python` (https://pypi.org/project/kafka-python/) to the worker containers.  I *think* this doesn't have any additional dependencies.

i've also been able to add a fairly simple webhook/callback script that will produce the task results to a topic, and also updated the docker-compose file to include kafka and zookeeper (though i'll be honest, i'm not sure whether zookeeper is actually required any longer).  i'm planning to clean up and improve the script this week after i do a bit more testing.

If there is interest to add it i'll be happy to open a PR with what i've done after I clean it up a bit and do a little more testing, to get the process started.

Thanks,

Will

**Comment by tbotnz** [comment]
moved to https://github.com/tbotnz/netpalm-kafka-webhook
