### ISSUE TITLE
Issue Huawei netconf

### ISSUE THREAD

**Issue by diorgesl** [tbotnz/netpalm#158]
I'm having this problem with Huawei NETCONF, is this a ncclient problem?
Task error:

      "Invalid tag name '<Element {urn:ietf:params:xml:ns:netconf:base:1.0}rpc at 0x7fd021d7d380>'",
      "failed: Invalid tag name '<Element {urn:ietf:params:xml:ns:netconf:base:1.0}rpc at 0x7fd021d7d380>'"
      
My body:
```
{
  "library": "ncclient",
  "connection_args": {
    "host": "1.1.2.3",
    "username": "user",
    "password": "pass",
    "port": 830,
    "hostkey_verify": false,
    "device_params" : { "name": "huawei"}
  },
  "args": {
    "rpc": "<get-config></get-config>",
    "render_json":true
  },
  "queue_strategy": "fifo"
}
```

**Comment by tbotnz** [comment]
no response
