### ISSUE TITLE
Service-template dry-run option is not dere

### ISSUE THREAD

**Issue by Minal1409** [tbotnz/netpalm#20]
Please add dry-run option for create delete operation in service template. This can be provided as napalm library has this inbuilt feature

**Comment by tbotnz** [comment]
Hi,

Can you provide more information surrounding the use case, happy to look into it

**Comment by Minal1409** [comment]
Like we have dry-run feature for the jinja 2 templates. Dry-run feature  should also be dere for service templates. This will help us to verify the config generated by service templates.

We can have one variable like dry-run : true which will direct netpalm not to commit config , rather than only generate config and give to user
