### ISSUE TITLE
Why to specify args for service jinja2 template. Unnecessary args mapping in service template. 

### ISSUE THREAD

**Issue by Minal1409** [tbotnz/netpalm#21]
Args will come from restapi call so can't be directly linked to jinja2 template called.
If we have 20 variables for jinja2 variable then each one needs to be mapped in service template and then value to be rendered from rest API call

**Comment by tbotnz** [comment]
you need to use j2config argument on your setconfigs, then you can use the " | tojson " Jinja2 filter. see example [here](https://github.com/tbotnz/netpalm/blob/master/backend/plugins/service_templates/ip_int_service.j2)

**Comment by Minal1409** [comment]
thanks
