### ISSUE TITLE
Cache TTL can currently exceed request TTL.  This should not be permitted.

### ISSUE THREAD

**Issue by wrgeorge1983** [tbotnz/netpalm#62]
Since what's actually cached is the Task metadata, and not the actual result, this should not be permitted.

Either:
* raise an error
* set cache_ttl to `min(cache_ttl, response_ttl)` 
* set response_ttl to `max(cache_ttl, response_ttl)`

I don't have any firm opinions on which way we go, but we should do one of those

**Comment by tbotnz** [comment]
To fix this we'd have to keep the cache_ttl in sync with the redis_task_ttl, any simple solution to do this would make sense

**Comment by tbotnz** [comment]
#92
