### ISSUE TITLE
Being able to pull cache items directly is probably more a liability than it's worth

### ISSUE THREAD

**Issue by wrgeorge1983** [tbotnz/netpalm#67]
Listing them is, I think, fine.  But pulling them individually is just another way for someone with the Netpalm API Key to snoop on any result obtained by any other user :/

**Comment by tbotnz** [comment]
this is fine to leave as is for now
- a different strategy needs to be implemented to solve this problem all together
- the same can be done with the job id
- a better solution would be multiple API keys with each API key only able to access its jobs

**Comment by tbotnz** [comment]
closing for now have added to the trello board support multiple API keys
