### ISSUE TITLE
TFSM template addtemplate route won't create a new section for a new driver

### ISSUE THREAD

**Issue by wrgeorge1983** [tbotnz/netpalm#72]
e.g. this "completes" just fine but never shows up in "gettemplates" output.  Not sure if it's just the index rewrite that's failing or what.

```json
{
	"key": "",
	"driver": "cisgo_foo",
	"command": "show asdf events"
}
```

**Comment by tbotnz** [comment]
@wrgeorge1983 is this still an issue ?

**Comment by wrgeorge1983** [comment]
Quick validation indicates yes.  I'll take a look.

**Comment by tbotnz** [comment]
You are my hero

**Comment by hanunes** [comment]
Good afternoon, I'm having this same issue. After I add the template, it says it was added, when I go and get the templates, it is not there, but after checking in the container, the template is in the folder.

Do you have any idea what could be wrong? I'm using the latest master branch commit.

**Comment by wrgeorge1983** [comment]
@hanunes could you show example of the payload you used to submit to Netpalm?  ideally the actual json that was sent.  I'll see if I can reproduce.

**Comment by hanunes** [comment]
Sure. So to clarify a bit more, this only happens in the second template I add for a specific driver (generic, linux, etc.).

`{
  "key": "<any nornir key>",
  "driver": "generic",
  "command": "test1"
}`

If you go to the endpoint to show the list of templates, it is there, and if you check the template itself, you get the template contents.

If, after you add the first one, you try the above payload, but with command being **test2**, you'll see it adds the template, but it does not appear on the list. Furthermore, you can see the content of the template file.

Even with diferent key values, the template does not appear on the list, but you can see its contents.
